# Generated by Django 5.2.3 on 2025-06-15 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requeststatistics',
            old_name='request',
            new_name='requests',
        ),
    ]
