# Generated by Django 5.2.3 on 2025-06-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_rename_request_requeststatistics_requests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requeststatistics',
            old_name='exception',
            new_name='exceptions',
        ),
    ]
