# Generated by Django 5.2.1 on 2025-06-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_experiment_article_experiment2'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='monthly_rate',
            field=models.IntegerField(default=0),
        ),
    ]
