# Generated by Django 5.2.3 on 2025-06-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_monthlysalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Job Descrition'),
        ),
        migrations.AlterField(
            model_name='position',
            name='monthly_rate',
            field=models.IntegerField(default=0, verbose_name='Monthly Rate'),
        ),
        migrations.AlterField(
            model_name='position',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
