# Generated by Django 5.2.3 on 2025-06-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Job Description'),
        ),
    ]
