# Generated by Django 5.2.3 on 2025-06-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_alter_position_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description_en',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='position',
            name='description_uk',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='Job Description'),
        ),
        migrations.AddField(
            model_name='position',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='position',
            name='title_uk',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
