# Generated by Django 5.2.3 on 2025-06-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_position_description_en_position_description_uk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.CharField(default='', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description_en',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description_uk',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='Description'),
        ),
    ]
